### ISSUE TITLE
Not enough permission

### ISSUE THREAD

**Issue by belarbi2733** [assistify/rcapps-gitlab#31]
I have this message : 

rocket.cat
14:01
Vous seul pouvez voir ce message
Not enough permission

**Comment by btittelbach** [comment]
ran into the same issue after following the install instructions, when testing via gitlab

**Comment by btittelbach** [comment]
- this is strange, since it seems to work for other gitlab users. The error just appears if my gitlab user which registered the webhook posts something to the gitlab issues.
- even more strange, the webhook suceeds with 200

corresponding rocket.chat error message in log:
```
{"level":50,"time":"2022-04-06T12:50:28.340Z","pid":78,"hostname":"rocketchat.redacted.info","name":"System","msg":"Error sending message: {}"} 
```

**Comment by nathanpalmer** [comment]
I'm running into the same issue. The Rocket Chat logs show this

```
=== UnHandledPromiseRejection ===
Error: Not enough permission
    at validateMessage (app/lib/server/functions/sendMessage.js:162:10)
    at sendMessage (app/lib/server/functions/sendMessage.js:210:2)
    at executeSendMessage (app/lib/server/methods/sendMessage.js:80:10)
    at app/apps/server/bridges/messages.ts:25:23
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
```
